### ISSUE TITLE
Error in Quick Demo

### ISSUE THREAD

**Issue by sidgan** [rkadlec/asreader#4]
I'm running the ./quick-start-cbt-ne.sh and I get the following error: 

```
ValueError: Variables must have names: [Elemwise{second,no_inplace}.0]
Validation files:

Best predictions to be copied:

Best validation model:
Traceback (most recent call last):
  File "text_comprehension/eval/copyBestPredictions.py", line 124, in <module>
    print bestValModel['params']
KeyError: 'params'

***** RUNNING THE FUSION SCRIPT *****

Models to be fused:


Ensemble (equal weights): 
/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "text_comprehension/eval/fusion.py", line 394, in <module>
    result = fuse_predictions(prediction_files)
  File "text_comprehension/eval/fusion.py", line 158, in fuse_predictions
    ensemble_accuracy = accuracy(numpy.mean(all_preds, 0))
  File "text_comprehension/eval/fusion.py", line 57, in accuracy
    for row in probas:
TypeError: 'numpy.float64' object is not iterable
```

I have the latest bricks as was suggested in #1 

There are no predictions or logs being produced. Could you tell me what I'm wrong?

Thank you!

**Comment by rkadlec** [comment]
One clarification: #1 suggests NOT to use the latest Blocks, instead you should use some older Blocks version, e.g.: pip install git+https://github.com/mila-udem/blocks.git@359afad119f8c6ac0ebc3cc6ec6e6475656babae
