### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by sidgan** [rkadlec/asreader#6]
I'm passing a subset of the training set in place of the original training set and I get the following attribute error from Theano. 

```
Parameters: 
	backward.state_to_state (384, 384).size=147456
	backward.state_to_gates (384, 768).size=294912
	backward.initial_state (384,).size=384
	fork_gate_inputs.b (768,).size=768
	fork_gate_inputs.W (384, 768).size=294912
	lookuptable.W (146, 384).size=56064
	fork_inputs.b (384,).size=384
	fork_inputs.W (384, 384).size=147456
	forward.state_to_state (384, 384).size=147456
	forward.state_to_gates (384, 768).size=294912
	forward.initial_state (384,).size=384
	fork_gate_inputs.b (768,).size=768
	fork_gate_inputs.W (384, 768).size=294912
	fork_inputs.b (384,).size=384
	fork_inputs.W (384, 384).size=147456
	backward.state_to_state (384, 384).size=147456
	backward.state_to_gates (384, 768).size=294912
	backward.initial_state (384,).size=384
	fork_gate_inputs.b (768,).size=768
	fork_gate_inputs.W (384, 768).size=294912
	fork_inputs.b (384,).size=384
	fork_inputs.W (384, 384).size=147456
	forward.state_to_state (384, 384).size=147456
	forward.state_to_gates (384, 768).size=294912
	forward.initial_state (384,).size=384
	fork_gate_inputs.b (768,).size=768
	fork_gate_inputs.W (384, 768).size=294912
	fork_inputs.b (384,).size=384
	fork_inputs.W (384, 384).size=147456
Trained parameters count: 3601152
    exp.execute()
  File "/home/ubuntu/asreader/asreader/text_comprehension/text_comprehension_base.py", line 413, in execute
    use_own_validation=True)
  File "/home/ubuntu/asreader/asreader/learning_experiment_base.py", line 370, in train
    main_loop.run()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/blocks/main_loop.py", line 197, in run
    reraise_as(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/blocks/utils/__init__.py", line 258, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/blocks/main_loop.py", line 183, in run
    while self._run_epoch():
  File "/home/ubuntu/.local/lib/python2.7/site-packages/blocks/main_loop.py", line 230, in _run_epoch
    self._run_extensions('before_epoch')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/blocks/main_loop.py", line 263, in _run_extensions
    extension.dispatch(CallbackName(method_name), *args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/blocks/extensions/__init__.py", line 338, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "/home/ubuntu/asreader/asreader/text_comprehension/monitoring.py", line 85, in do
    value_dict = self._evaluator.evaluate(self.data_stream)
  File "/home/ubuntu/asreader/asreader/text_comprehension/monitoring.py", line 323, in evaluate
    self.process_batch(batch)
  File "/home/ubuntu/asreader/asreader/text_comprehension/monitoring.py", line 296, in process_batch
    numerical_values = self._accumulate_fun(**batch)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 801, in __call__
    self[k] = arg
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 548, in __setitem__
    self.value[item] = value
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 505, in __setitem__
    s.value = value
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/link.py", line 468, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/tensor/type.py", line 123, in filter
    up_dtype = scal.upcast(self.dtype, data.dtype)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/scalar/basic.py", line 77, in upcast
    rval = str(z.dtype)
AttributeError: ('\'int\' object has no attribute \'dtype\', Container name "answer"\n\nOriginal exception:\n\tAttributeError: \'int\' object has no attribute \'dtype\', Container name "answer"', 'Container name "answer"')
Validation files:

Best predictions to be copied:

Best validation model:
Traceback (most recent call last):
  File "text_comprehension/eval/copyBestPredictions.py", line 124, in <module>
    print bestValModel['params']
KeyError: 'params'

***** RUNNING THE FUSION SCRIPT *****

Models to be fused:


Ensemble (equal weights): 
/home/ubuntu/.local/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/home/ubuntu/.local/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "text_comprehension/eval/fusion.py", line 394, in <module>
    result = fuse_predictions(prediction_files)
  File "text_comprehension/eval/fusion.py", line 158, in fuse_predictions
    ensemble_accuracy = accuracy(numpy.mean(all_preds, 0))
  File "text_comprehension/eval/fusion.py", line 57, in accuracy
    for row in probas:
TypeError: 'numpy.float64' object is not iterable
```

**Comment by rkadlec** [comment]
Hi, do you have an example from the new dataset? From what I can see there is some issue with the answer matrix.

**Comment by sidgan** [comment]
Hi, when I was parsing the original file I didn't realize it had two tabs between the answer and the answer candidates. This is what was causing the errors. 

Thank you for your reply.
