### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by dpappas** [rkadlec/asreader#9]
Could you explain what exactly is the problem ? 

i used  a cnn dataset_type

the full error is 

`ERROR:blocks.main_loop:Error occured during training.

Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error. Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "./text_comprehension/as_reader.py", line 166, in <module>
    exp.execute()
  File "/home/uname/ASReader/asreader/asreader/text_comprehension/text_comprehension_base.py", line 413, in execute
    use_own_validation=True)
  File "/home/uname/ASReader/asreader/asreader/learning_experiment_base.py", line 370, in train
    main_loop.run()
  File "/home/uname/.local/lib/python2.7/site-packages/blocks/main_loop.py", line 197, in run
    reraise_as(e)
  File "/home/uname/.local/lib/python2.7/site-packages/blocks/utils/__init__.py", line 258, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/home/uname/.local/lib/python2.7/site-packages/blocks/main_loop.py", line 183, in run
    while self._run_epoch():
  File "/home/uname/.local/lib/python2.7/site-packages/blocks/main_loop.py", line 230, in _run_epoch
    self._run_extensions('before_epoch')
  File "/home/uname/.local/lib/python2.7/site-packages/blocks/main_loop.py", line 263, in _run_extensions
    extension.dispatch(CallbackName(method_name), *args)
  File "/home/uname/.local/lib/python2.7/site-packages/blocks/extensions/__init__.py", line 338, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "/media/large_space_1/uname/ASReader/asreader/asreader/text_comprehension/monitoring.py", line 137, in do
    context_strs = get_str_masked(self.context,i)
  File "/media/large_space_1/uname/ASReader/asreader/asreader/text_comprehension/monitoring.py", line 132, in get_str_masked
    return ints_to_words(word_ixs[:true_length])
TypeError: slice indices must be integers or None or have an __index__ method

Original exception:
        TypeError: slice indices must be integers or None or have an __index__ method`

**Comment by rkadlec** [comment]
Do you use the standard CNN dataset?

**Comment by dpappas** [comment]
No i do not. 

I created my own dataset but used the same format as cnn dataset

**Comment by rkadlec** [comment]
Since it works with the original CNN dataset there will be probably some example in our dataset that causes this issue. Can you create a minimal example where it fails?

**Comment by dpappas** [comment]
Unfortunately it does not work with the original CNN dataset either.

It produces the same error

**Comment by dpappas** [comment]
I solved it. 

After much research i found out that the new version of numpy is your problem.

I used numpy 1.12.0
When i downgraded to numpy 1.12.0 it worked. 

Maybe the developpers should consider adding a requirements file including the versions of the packages.
